{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "agent-warden.labels" . | nindent 4 }}
    kubernetes.io/metadata.name: {{ .Values.namespace.name }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
{{- end }}
