apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - ../../crds/scopedagent.yaml
  - ../../crds/blockedaction.yaml
  - ../../crds/agentactionrequest.yaml
  - 10-guardrails-service.yaml
  - 20-operator-rbac.yaml
  - 21-operator.yaml
  - 30-admission-webhook.yaml
  - 31-validating-webhook.yaml
  - 40-dashboard.yaml
